name: Build viewer
on:
  workflow_dispatch:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
         fetch-depth: 1

      - name: Debug
        run: set

      - name: configure
        run: cmake -S src -B build

      - name: build
        run: cmake --build build

      - name: publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.zip
          path: build/playground

      - name: Debug
        run: echo "${{github.ref_name}}"
      - name: Debug
        run: echo "${GITHUB_REF_NAME}"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/playgrou*
