name: Build viewer
on:
  workflow_dispatch:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
         fetch-depth: 1

      - name: Debug
        run: set

      - name: configure
        run: cmake -S src -B build

      - name: build
        run: cmake --build build

      - name: publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.zip
          path: build/playground

      - name: Debug
        run: echo "${{github.ref_name}}"
      - name: Debug
        run: echo "${GITHUB_REF_NAME}"

      - name: create release
        run: |
             curl -X POST  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/Nicky-D/actions-playground/releases \
             -d '{"tag_name": "${GITHUB_REF_NAME}","name": "${{github.github.ref_name}}","body":"Test release","draft":true,"prerelease":true,"generate_release_notes":true}'
