name: Build viewer
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
         fetch-depth: 1
      -name: Debug
       run: set

      - name: configure
        run: cmake -S src -B build

      - name: build
        run: cmake --build build

      - name: publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.zip
          path: build/playground